# Generated by Django 2.0.4 on 2018-06-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(max_length=45)),
                ('UserName', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
                ('Secret', models.CharField(max_length=45)),
                ('DeviceType', models.CharField(choices=[('R', 'Router'), ('L2S', 'Layer2Switch'), ('L3S', 'Layer3Switch')], max_length=20)),
                ('DeviceLocation', models.CharField(choices=[('C', 'Core'), ('Agg', 'Aggregation'), ('Acc', 'Access')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ipv4Address', models.CharField(max_length=45)),
                ('InterfaceDescription', models.CharField(max_length=100)),
                ('InterfaceStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopologyName', models.CharField(max_length=45)),
                ('TopologyDescription', models.CharField(max_length=200)),
                ('NetworkAddress', models.CharField(max_length=45)),
                ('DomainName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Controller.Port')),
                ('InterfacePort', models.CharField(max_length=5)),
                ('InterfaceSlot', models.CharField(max_length=5)),
                ('Switchport', models.BooleanField(default=False)),
                ('InterfaceType', models.CharField(choices=[('Fa', 'FastEthernet'), ('Gi', 'GigabitEtherne'), ('Eth', 'Ethernet'), ('Se', 'Serial')], max_length=20)),
            ],
            bases=('Controller.port',),
        ),
        migrations.CreateModel(
            name='InterfaceVlan',
            fields=[
                ('port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Controller.Port')),
            ],
            bases=('Controller.port',),
        ),
        migrations.CreateModel(
            name='LoopBack',
            fields=[
                ('port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Controller.Port')),
            ],
            bases=('Controller.port',),
        ),
        migrations.CreateModel(
            name='SubInterface',
            fields=[
                ('port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Controller.Port')),
                ('InterfaceRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controller.Interface')),
            ],
            bases=('Controller.port',),
        ),
        migrations.AddField(
            model_name='port',
            name='DeviceRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controller.Device'),
        ),
        migrations.AddField(
            model_name='port',
            name='LinkRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controller.Link'),
        ),
        migrations.AddField(
            model_name='link',
            name='TopologyRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controller.Topology'),
        ),
        migrations.AddField(
            model_name='device',
            name='TopologyRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controller.Topology'),
        ),
    ]
